services:
  db:
    image: postgres:16
    container_name: fl4re_db
    environment:
      POSTGRES_USER: microblog
      POSTGRES_PASSWORD: microblog_dev
      POSTGRES_DB: fl4re_development
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U microblog"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
